-- ONE-SHOT: fixes college text + creates new tables + loads cutoffs

-- Seed CollegeClash colleges (run AFTER schema.sql). Safe to re-run.
insert into public.colleges (id, name, city, type, accent, tagline, image, thumb, specialities, factors) values
('iit-madras', 'IIT Madras', 'Chennai, Tamil Nadu', 'Engineering & Technology', '#00e0ff', 'Ranked India''s #1 institute by NIRF, year after year.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/IIT_Madras_campus_main_gate.jpg/1280px-IIT_Madras_campus_main_gate.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/IIT_Madras_campus_main_gate.jpg/330px-IIT_Madras_campus_main_gate.jpg', '["Data Science (online BSc)","Ocean Engineering","Research & patents","Deep-tech incubation"]'::jsonb, '{"ranking":1,"reputation":3,"avgPackage":22,"medianPackage":19.6,"highestPackage":192,"placementRate":78,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":8,"research":97,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":620,"location":"Urban · Chennai"}'::jsonb),
('iit-delhi', 'IIT Delhi', 'New Delhi', 'Engineering & Technology', '#3b82f6', 'Capital powerhouse with elite recruiter access.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Bridge_connecting_Central_Library_with_the_Main_Building%2C_IIT_Delhi.jpg/1280px-Bridge_connecting_Central_Library_with_the_Main_Building%2C_IIT_Delhi.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Bridge_connecting_Central_Library_with_the_Main_Building%2C_IIT_Delhi.jpg/330px-Bridge_connecting_Central_Library_with_the_Main_Building%2C_IIT_Delhi.jpg', '["Computer Science","Electrical Engineering","Textile Technology","Policy & management"]'::jsonb, '{"ranking":2,"reputation":3,"avgPackage":25,"medianPackage":20,"highestPackage":205,"placementRate":87,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":9,"research":93,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":320,"location":"Urban · Delhi"}'::jsonb),
('iit-bombay', 'IIT Bombay', 'Mumbai, Maharashtra', 'Engineering & Technology', '#7c5cff', 'India''s flagship for tech, design and startups.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Night_view_of_campus_buildings_at_IIT_Bombay.jpg/1280px-Night_view_of_campus_buildings_at_IIT_Bombay.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Night_view_of_campus_buildings_at_IIT_Bombay.jpg/330px-Night_view_of_campus_buildings_at_IIT_Bombay.jpg', '["Computer Science","Aerospace Engineering","E-Cell & startups","Design (IDC)"]'::jsonb, '{"ranking":3,"reputation":3,"avgPackage":23.5,"medianPackage":17.9,"highestPackage":367,"placementRate":75,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":9,"research":95,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":545,"location":"Urban · Mumbai"}'::jsonb),
('iit-kanpur', 'IIT Kanpur', 'Kanpur, Uttar Pradesh', 'Engineering & Technology', '#8b5cf6', 'Pioneer of computer science education in India.', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Single_Bench_in_front_of_Open_Green_Ground_Spaces_at_the_Kalyanpur_campus_of_IIT_Kanpur.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Single_Bench_in_front_of_Open_Green_Ground_Spaces_at_the_Kalyanpur_campus_of_IIT_Kanpur.jpg/330px-Single_Bench_in_front_of_Open_Green_Ground_Spaces_at_the_Kalyanpur_campus_of_IIT_Kanpur.jpg', '["Computer Science","Aerospace Engineering","Robotics","Flight laboratory"]'::jsonb, '{"ranking":4,"reputation":3,"avgPackage":26.3,"medianPackage":21.7,"highestPackage":190,"placementRate":80,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":9,"research":94,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":1055,"location":"Suburban · Kanpur"}'::jsonb),
('iit-kharagpur', 'IIT Kharagpur', 'Kharagpur, West Bengal', 'Engineering & Technology', '#6366f1', 'The original IIT and the largest campus of them all.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Main_Entrance_-_IIT_Campus_-_Kharagpur_-_West_Midnapore_2015-09-28_4074.JPG/1280px-Main_Entrance_-_IIT_Campus_-_Kharagpur_-_West_Midnapore_2015-09-28_4074.JPG', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Main_Entrance_-_IIT_Campus_-_Kharagpur_-_West_Midnapore_2015-09-28_4074.JPG/330px-Main_Entrance_-_IIT_Campus_-_Kharagpur_-_West_Midnapore_2015-09-28_4074.JPG', '["Largest IIT campus","Mining Engineering","Rajiv Gandhi School of Law","Ocean & naval"]'::jsonb, '{"ranking":5,"reputation":3,"avgPackage":24,"medianPackage":19,"highestPackage":200,"placementRate":78,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":10,"research":92,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":2100,"location":"Small town · Kharagpur"}'::jsonb),
('iit-roorkee', 'IIT Roorkee', 'Roorkee, Uttarakhand', 'Engineering & Technology', '#0ea5e9', 'World leader in civil and earthquake engineering.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Architecture_and_Planning_building%2C_IIT_Roorkee.jpg/1280px-Architecture_and_Planning_building%2C_IIT_Roorkee.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Architecture_and_Planning_building%2C_IIT_Roorkee.jpg/330px-Architecture_and_Planning_building%2C_IIT_Roorkee.jpg', '["Civil Engineering","Earthquake Engineering","Hydrology","Water resources"]'::jsonb, '{"ranking":6,"reputation":3,"avgPackage":20,"medianPackage":16,"highestPackage":160,"placementRate":80,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":11,"research":89,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":365,"location":"Small town · Roorkee"}'::jsonb),
('iit-guwahati', 'IIT Guwahati', 'Guwahati, Assam', 'Engineering & Technology', '#22d3ee', 'One of the most scenic tech campuses on Earth.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/IIT_Guwahati_Campus.JPG/1280px-IIT_Guwahati_Campus.JPG', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/IIT_Guwahati_Campus.JPG/330px-IIT_Guwahati_Campus.JPG', '["Design","Biotechnology","Riverfront campus","Nanotechnology"]'::jsonb, '{"ranking":7,"reputation":3,"avgPackage":25.75,"medianPackage":21.6,"highestPackage":240,"placementRate":80,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":10,"research":88,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":700,"location":"Suburban · Guwahati"}'::jsonb),
('iit-hyderabad', 'IIT Hyderabad', 'Hyderabad, Telangana', 'Engineering & Technology', '#a855f7', 'Young, research-first IIT with an AI edge.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Iith_temp_campus.jpg/1280px-Iith_temp_campus.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Iith_temp_campus.jpg/330px-Iith_temp_campus.jpg', '["Artificial Intelligence","Design","Fractal academic system","Entrepreneurship"]'::jsonb, '{"ranking":8,"reputation":3,"avgPackage":22.5,"medianPackage":19,"highestPackage":90,"placementRate":80,"recruiters":3,"fees":9,"feesRange":"₹8–10 L","facultyRatio":9,"research":90,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":576,"location":"Suburban · Hyderabad"}'::jsonb),
('nit-trichy', 'NIT Trichy', 'Tiruchirappalli, Tamil Nadu', 'Engineering & Technology', '#38bdf8', 'The undisputed #1 among India''s NITs.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Clock_Tower_NITT.jpg/1280px-Clock_Tower_NITT.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Clock_Tower_NITT.jpg/330px-Clock_Tower_NITT.jpg', '["Strong core branches","Powerful alumni network","Festival culture (Pragyan)","Production engineering"]'::jsonb, '{"ranking":9,"reputation":2,"avgPackage":16,"medianPackage":12.8,"highestPackage":70,"placementRate":89,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":13,"research":78,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":800,"location":"Suburban · Trichy"}'::jsonb),
('iit-bhu', 'IIT (BHU) Varanasi', 'Varanasi, Uttar Pradesh', 'Engineering & Technology', '#6366f1', 'An IIT with the soul of a century-old institution.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Limbdi_Hostel%2C_IIT-BHU.jpg/1280px-Limbdi_Hostel%2C_IIT-BHU.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Limbdi_Hostel%2C_IIT-BHU.jpg/330px-Limbdi_Hostel%2C_IIT-BHU.jpg', '["Ceramic & Metallurgical Engineering","Mining","Engineering breadth","Heritage (ex-IT BHU)"]'::jsonb, '{"ranking":10,"reputation":3,"avgPackage":18,"medianPackage":14.4,"highestPackage":100,"placementRate":78,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":11,"research":86,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":400,"location":"Urban · Varanasi"}'::jsonb),
('vit-vellore', 'VIT Vellore', 'Vellore, Tamil Nadu', 'Engineering (Private)', '#fb7185', 'Massive recruiter base and a slick modern campus.', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Main_administrative_building%2C_Vellore_Institute_of_Technology.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Main_administrative_building%2C_Vellore_Institute_of_Technology.jpg/330px-Main_administrative_building%2C_Vellore_Institute_of_Technology.jpg', '["600+ recruiters","Modern infrastructure","Flexible credit system (FFCS)","International tie-ups"]'::jsonb, '{"ranking":11,"reputation":2,"avgPackage":9.9,"medianPackage":7.9,"highestPackage":88,"placementRate":82,"recruiters":3,"fees":12,"feesRange":"₹8–16 L","facultyRatio":18,"research":70,"infrastructure":3,"accreditation":"NAAC A++","exam":"VITEEE","campusAcres":372,"location":"Suburban · Vellore"}'::jsonb),
('iit-dhanbad', 'IIT (ISM) Dhanbad', 'Dhanbad, Jharkhand', 'Engineering & Technology', '#f59e0b', 'India''s home of mining & petroleum engineering.', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Senior_Academic_Hostel_at_IIT_Dhanbad.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Senior_Academic_Hostel_at_IIT_Dhanbad.jpg/330px-Senior_Academic_Hostel_at_IIT_Dhanbad.jpg', '["Mining Engineering (India''s best)","Petroleum Engineering","Earth sciences","Legacy as ISM"]'::jsonb, '{"ranking":15,"reputation":2,"avgPackage":14,"medianPackage":11.2,"highestPackage":80,"placementRate":75,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":12,"research":84,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":393,"location":"Urban · Dhanbad"}'::jsonb),
('iit-indore', 'IIT Indore', 'Indore, Madhya Pradesh', 'Engineering & Technology', '#8b5cf6', 'Young, research-driven and rising fast.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/PACL_Campus%2C_IIT_Indore.jpg/1280px-PACL_Campus%2C_IIT_Indore.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/PACL_Campus%2C_IIT_Indore.jpg/330px-PACL_Campus%2C_IIT_Indore.jpg', '["High research output","Compact elite batches","CS & Metallurgy","Modern PACL campus"]'::jsonb, '{"ranking":16,"reputation":2,"avgPackage":17,"medianPackage":13.6,"highestPackage":64,"placementRate":80,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":10,"research":88,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":501,"location":"Rural · Indore"}'::jsonb),
('nit-surathkal', 'NIT Surathkal', 'Surathkal, Karnataka', 'Engineering & Technology', '#06b6d4', 'Beachfront NIT with strong core engineering.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Kite_festival_2_%2C_NITK_Beach.jpg/1280px-Kite_festival_2_%2C_NITK_Beach.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Kite_festival_2_%2C_NITK_Beach.jpg/330px-Kite_festival_2_%2C_NITK_Beach.jpg', '["Coastal campus","Civil & Mechanical","Mining","Information Technology"]'::jsonb, '{"ranking":17,"reputation":2,"avgPackage":16,"medianPackage":12.8,"highestPackage":55,"placementRate":84,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":13,"research":76,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":295,"location":"Coastal · Mangalore"}'::jsonb),
('iit-gandhinagar', 'IIT Gandhinagar', 'Gandhinagar, Gujarat', 'Engineering & Technology', '#a855f7', 'Research intensity with a liberal-arts twist.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Entrance_Close_Guest_House_IITGN_Gujarat_Sep25_A7CR_07901.jpg/1280px-Entrance_Close_Guest_House_IITGN_Gujarat_Sep25_A7CR_07901.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Entrance_Close_Guest_House_IITGN_Gujarat_Sep25_A7CR_07901.jpg/330px-Entrance_Close_Guest_House_IITGN_Gujarat_Sep25_A7CR_07901.jpg', '["High research per faculty","Liberal-arts electives","Foundation programme","Award-winning campus"]'::jsonb, '{"ranking":18,"reputation":2,"avgPackage":16,"medianPackage":12.8,"highestPackage":60,"placementRate":78,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":9,"research":90,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":400,"location":"Urban · Gandhinagar"}'::jsonb),
('nit-rourkela', 'NIT Rourkela', 'Rourkela, Odisha', 'Engineering & Technology', '#38bdf8', 'A top-tier NIT with strong core and research.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/NIT_rourkela.jpg/1280px-NIT_rourkela.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/NIT_rourkela.jpg/330px-NIT_rourkela.jpg', '["Metallurgy & Materials","Strong research","Vibrant campus life"]'::jsonb, '{"ranking":19,"reputation":2,"avgPackage":15,"medianPackage":12,"highestPackage":80,"placementRate":85,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":13,"research":78,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":650,"location":"Suburban · Rourkela"}'::jsonb),
('bits-pilani', 'BITS Pilani', 'Pilani, Rajasthan', 'Engineering (Private)', '#f472b6', 'No reservations, pure merit — the private elite.', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/BITS-Pilani_campus_aerial_view.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/BITS-Pilani_campus_aerial_view.jpg/330px-BITS-Pilani_campus_aerial_view.jpg', '["Flexible curriculum","Practice School internships","Entrepreneurship","Dual degrees"]'::jsonb, '{"ranking":20,"reputation":3,"avgPackage":18,"medianPackage":14.4,"highestPackage":60,"placementRate":91,"recruiters":3,"fees":22.5,"feesRange":"₹20–25 L","facultyRatio":12,"research":80,"infrastructure":3,"accreditation":"NAAC A++","exam":"BITSAT","campusAcres":328,"location":"Small town · Pilani"}'::jsonb),
('nit-warangal', 'NIT Warangal', 'Warangal, Telangana', 'Engineering & Technology', '#06b6d4', 'Often the #1 NIT — elite among the NITs.', '', '', '["Top CSE placements","Powerful alumni","Oldest NIT (1959)"]'::jsonb, '{"ranking":21,"reputation":2,"avgPackage":15.6,"medianPackage":12.5,"highestPackage":88,"placementRate":80,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":13,"research":78,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":250,"location":"Suburban · Warangal"}'::jsonb),
('iit-ropar', 'IIT Ropar', 'Rupnagar, Punjab', 'Engineering & Technology', '#0ea5e9', 'Tiny batch, outsized research citations.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/IIT_Ropar_-_Main_Building_of_the_Transit_Campus.JPG/1280px-IIT_Ropar_-_Main_Building_of_the_Transit_Campus.JPG', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/IIT_Ropar_-_Main_Building_of_the_Transit_Campus.JPG/330px-IIT_Ropar_-_Main_Building_of_the_Transit_Campus.JPG', '["Top research citations","AI & Biomedical Engineering","Per-faculty output","Punjab''s IIT"]'::jsonb, '{"ranking":22,"reputation":2,"avgPackage":15,"medianPackage":12,"highestPackage":60,"placementRate":72,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":10,"research":89,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":525,"location":"Small town · Rupnagar"}'::jsonb),
('nit-calicut', 'NIT Calicut', 'Kozhikode, Kerala', 'Engineering & Technology', '#0ea5e9', 'Kerala''s premier NIT with a green campus.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Chemical_Engineering_Department_Building_NIT_Calicut.jpg/1280px-Chemical_Engineering_Department_Building_NIT_Calicut.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Chemical_Engineering_Department_Building_NIT_Calicut.jpg/330px-Chemical_Engineering_Department_Building_NIT_Calicut.jpg', '["Architecture","Strong core branches","Lush campus"]'::jsonb, '{"ranking":25,"reputation":2,"avgPackage":9.6,"medianPackage":8,"highestPackage":50,"placementRate":82,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":13,"research":76,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":300,"location":"Suburban · Calicut"}'::jsonb),
('dtu', 'Delhi Technological University', 'New Delhi', 'Engineering & Technology', '#60a5fa', 'Delhi''s legacy engineering school (formerly DCE).', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/DELHI_TECHNOLOGICAL_UNIVERSITY%2C_%28East_Delhi_Campus%29.jpg/1280px-DELHI_TECHNOLOGICAL_UNIVERSITY%2C_%28East_Delhi_Campus%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/DELHI_TECHNOLOGICAL_UNIVERSITY%2C_%28East_Delhi_Campus%29.jpg/330px-DELHI_TECHNOLOGICAL_UNIVERSITY%2C_%28East_Delhi_Campus%29.jpg', '["Delhi-NCR placements","Software roles","Legacy (ex-DCE)","Strong CSE/IT"]'::jsonb, '{"ranking":27,"reputation":2,"avgPackage":13,"medianPackage":10.4,"highestPackage":64,"placementRate":80,"recruiters":2,"fees":8,"feesRange":"₹7–9 L","facultyRatio":15,"research":72,"infrastructure":2,"accreditation":"NAAC A","exam":"JEE Main","campusAcres":167,"location":"Urban · Delhi"}'::jsonb),
('iit-jodhpur', 'IIT Jodhpur', 'Jodhpur, Rajasthan', 'Engineering & Technology', '#d97706', 'Desert-campus IIT betting big on AI & health.', '', '', '["AI & Digital Health","Interdisciplinary labs","Modern desert campus","Rajasthan''s IIT"]'::jsonb, '{"ranking":28,"reputation":2,"avgPackage":14,"medianPackage":11.2,"highestPackage":55,"placementRate":72,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":11,"research":83,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":852,"location":"Suburban · Jodhpur"}'::jsonb),
('iit-mandi', 'IIT Mandi', 'Mandi, Himachal Pradesh', 'Engineering & Technology', '#22d3ee', 'An IIT in the Himalayan foothills.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Top_View_Panorama_North_Campus_IIT_Mandi.jpg/1280px-Top_View_Panorama_North_Campus_IIT_Mandi.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Top_View_Panorama_North_Campus_IIT_Mandi.jpg/330px-Top_View_Panorama_North_Campus_IIT_Mandi.jpg', '["Himalayan campus","Data Science & AI","Interdisciplinary research","Adventure & outdoors"]'::jsonb, '{"ranking":31,"reputation":2,"avgPackage":15,"medianPackage":12,"highestPackage":50,"placementRate":75,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":11,"research":85,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":538,"location":"Hill town · Mandi"}'::jsonb),
('iit-patna', 'IIT Patna', 'Patna, Bihar', 'Engineering & Technology', '#3b82f6', 'Eastern India''s growing tech hub.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/IIT_Patna_mechanical_block_back_view.jpg/1280px-IIT_Patna_mechanical_block_back_view.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/IIT_Patna_mechanical_block_back_view.jpg/330px-IIT_Patna_mechanical_block_back_view.jpg', '["Computer Science","Growing research","Affordable living","Strong core branches"]'::jsonb, '{"ranking":34,"reputation":2,"avgPackage":14,"medianPackage":11.2,"highestPackage":50,"placementRate":75,"recruiters":2,"fees":9,"feesRange":"₹8–10 L","facultyRatio":11,"research":82,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":501,"location":"Suburban · Patna"}'::jsonb),
('nit-nagpur', 'VNIT Nagpur', 'Nagpur, Maharashtra', 'Engineering & Technology', '#22d3ee', 'Central India''s leading NIT.', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/VNIT_Nagpur_main.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/VNIT_Nagpur_main.jpg/330px-VNIT_Nagpur_main.jpg', '["Civil & Mining","Central location","Strong recruiters"]'::jsonb, '{"ranking":39,"reputation":2,"avgPackage":13,"medianPackage":10.4,"highestPackage":45,"placementRate":82,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":75,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":215,"location":"Urban · Nagpur"}'::jsonb),
('nit-silchar', 'NIT Silchar', 'Silchar, Assam', 'Engineering & Technology', '#2dd4bf', 'A scenic NIT in the hills of the Northeast.', '', '', '["Picturesque lakeside campus","Core engineering","Close-knit batches"]'::jsonb, '{"ranking":40,"reputation":2,"avgPackage":13.5,"medianPackage":10.8,"highestPackage":53,"placementRate":78,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":70,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":625,"location":"Suburban · Silchar"}'::jsonb),
('nit-jaipur', 'MNIT Jaipur', 'Jaipur, Rajasthan', 'Engineering & Technology', '#14b8a6', 'Rajasthan''s flagship NIT in the Pink City.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/MNIT_North_East_View_of_Campus_and_Lecture_Theatre_Complex.jpg/1280px-MNIT_North_East_View_of_Campus_and_Lecture_Theatre_Complex.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/MNIT_North_East_View_of_Campus_and_Lecture_Theatre_Complex.jpg/330px-MNIT_North_East_View_of_Campus_and_Lecture_Theatre_Complex.jpg', '["Architecture & Planning","Strong placements","Heritage city"]'::jsonb, '{"ranking":43,"reputation":2,"avgPackage":14,"medianPackage":11.2,"highestPackage":42,"placementRate":82,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":74,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":317,"location":"Urban · Jaipur"}'::jsonb),
('nit-durgapur', 'NIT Durgapur', 'Durgapur, West Bengal', 'Engineering & Technology', '#60a5fa', 'An established NIT in industrial Bengal.', '', '', '["Core engineering","Industry ties","Active campus culture"]'::jsonb, '{"ranking":44,"reputation":2,"avgPackage":11,"medianPackage":8.8,"highestPackage":45,"placementRate":78,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":70,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":190,"location":"Urban · Durgapur"}'::jsonb),
('nit-delhi', 'NIT Delhi', 'New Delhi', 'Engineering & Technology', '#3b82f6', 'A young NIT with a prime capital location.', 'https://upload.wikimedia.org/wikipedia/commons/8/8f/NIT_Delhi_Areal_View.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/NIT_Delhi_Areal_View.jpg/330px-NIT_Delhi_Areal_View.jpg', '["Delhi-NCR placements","CSE focus","New campus"]'::jsonb, '{"ranking":45,"reputation":2,"avgPackage":14,"medianPackage":11.2,"highestPackage":50,"placementRate":80,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":72,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":51,"location":"Urban · Delhi"}'::jsonb),
('iiit-hyderabad', 'IIIT Hyderabad', 'Hyderabad, Telangana', 'Computer Science & IT', '#818cf8', 'Tiny, elite, and the highest CS packages in India.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/IIIT_Hyderabad_campus_in_Hyderabad_02.jpg/1280px-IIIT_Hyderabad_campus_in_Hyderabad_02.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/IIIT_Hyderabad_campus_in_Hyderabad_02.jpg/330px-IIIT_Hyderabad_campus_in_Hyderabad_02.jpg', '["CS research powerhouse","Honours & dual degrees","Highest CS packages","Product company pipeline"]'::jsonb, '{"ranking":47,"reputation":3,"avgPackage":30,"medianPackage":24,"highestPackage":69,"placementRate":99,"recruiters":3,"fees":17,"feesRange":"₹16–18 L","facultyRatio":10,"research":90,"infrastructure":3,"accreditation":"NAAC A++","exam":"JEE Main","campusAcres":66,"location":"Urban · Hyderabad"}'::jsonb),
('iit-bhubaneswar', 'IIT Bhubaneswar', 'Bhubaneswar, Odisha', 'Engineering & Technology', '#14b8a6', 'Earth, ocean and core engineering by the coast.', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Master_Plan_of_IIT_Bhubaneswar_Main_Building.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Master_Plan_of_IIT_Bhubaneswar_Main_Building.jpg/330px-Master_Plan_of_IIT_Bhubaneswar_Main_Building.jpg', '["Earth & ocean sciences","Green campus","Core engineering","Odisha''s IIT"]'::jsonb, '{"ranking":54,"reputation":2,"avgPackage":14,"medianPackage":11.2,"highestPackage":50,"placementRate":72,"recruiters":1,"fees":9,"feesRange":"₹8–10 L","facultyRatio":11,"research":83,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":936,"location":"Suburban · Bhubaneswar"}'::jsonb),
('nit-patna', 'NIT Patna', 'Patna, Bihar', 'Engineering & Technology', '#0891b2', 'Bihar''s NIT with a long engineering legacy.', 'https://upload.wikimedia.org/wikipedia/commons/c/cc/NIT_Patna_campus.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/NIT_Patna_campus.jpg/330px-NIT_Patna_campus.jpg', '["Core branches","Affordable","Growing campus"]'::jsonb, '{"ranking":55,"reputation":2,"avgPackage":11,"medianPackage":8.8,"highestPackage":45,"placementRate":75,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":70,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":125,"location":"Suburban · Patna"}'::jsonb),
('nit-jalandhar', 'NIT Jalandhar', 'Jalandhar, Punjab', 'Engineering & Technology', '#0e7490', 'Punjab''s NIT with solid core engineering.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/NIT_Jalandhar_Campus.jpg/1280px-NIT_Jalandhar_Campus.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/NIT_Jalandhar_Campus.jpg/330px-NIT_Jalandhar_Campus.jpg', '["Industrial & Production","Strong sports","Compact campus"]'::jsonb, '{"ranking":58,"reputation":2,"avgPackage":12,"medianPackage":9.6,"highestPackage":62,"placementRate":78,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":70,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":154,"location":"Urban · Jalandhar"}'::jsonb),
('nit-surat', 'SVNIT Surat', 'Surat, Gujarat', 'Engineering & Technology', '#0284c7', 'Gujarat''s NIT in the diamond city.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/SVNIT_Campus.JPG/1280px-SVNIT_Campus.JPG', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/SVNIT_Campus.JPG/330px-SVNIT_Campus.JPG', '["Civil & Chemical","Strong placements","Riverfront campus"]'::jsonb, '{"ranking":59,"reputation":2,"avgPackage":12,"medianPackage":9.6,"highestPackage":50,"placementRate":80,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":73,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":250,"location":"Urban · Surat"}'::jsonb),
('nit-allahabad', 'MNNIT Allahabad', 'Prayagraj, Uttar Pradesh', 'Engineering & Technology', '#2563eb', 'One of the strongest and oldest NITs.', 'https://upload.wikimedia.org/wikipedia/commons/8/83/MNNIT_Academic_building_new.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/MNNIT_Academic_building_new.jpg/330px-MNNIT_Academic_building_new.jpg', '["Top CSE & ECE","Powerful alumni","Heritage campus"]'::jsonb, '{"ranking":60,"reputation":2,"avgPackage":16.8,"medianPackage":13.4,"highestPackage":71,"placementRate":85,"recruiters":3,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":73,"infrastructure":3,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":222,"location":"Urban · Prayagraj"}'::jsonb),
('iit-tirupati', 'IIT Tirupati', 'Tirupati, Andhra Pradesh', 'Engineering & Technology', '#06b6d4', 'An emerging IIT in temple-town Tirupati.', '', '', '["Emerging research","Strong core branches","Scenic new campus","South India''s newer IIT"]'::jsonb, '{"ranking":61,"reputation":2,"avgPackage":13,"medianPackage":10.4,"highestPackage":45,"placementRate":70,"recruiters":1,"fees":9,"feesRange":"₹8–10 L","facultyRatio":12,"research":80,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":540,"location":"Suburban · Tirupati"}'::jsonb),
('iit-jammu', 'IIT Jammu', 'Jammu, Jammu & Kashmir', 'Engineering & Technology', '#818cf8', 'A modern IIT in India''s north.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/IIT_Jammu_Campus.jpg/1280px-IIT_Jammu_Campus.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/IIT_Jammu_Campus.jpg/330px-IIT_Jammu_Campus.jpg', '["AI & robotics","Modern facilities","Strategic location","Newer IIT"]'::jsonb, '{"ranking":62,"reputation":2,"avgPackage":13,"medianPackage":10.4,"highestPackage":45,"placementRate":70,"recruiters":1,"fees":9,"feesRange":"₹8–10 L","facultyRatio":12,"research":80,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":400,"location":"Suburban · Jammu"}'::jsonb),
('iit-palakkad', 'IIT Palakkad', 'Palakkad, Kerala', 'Engineering & Technology', '#2dd4bf', 'Kerala''s IIT in the green Western Ghats.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/IIT_Palakkad_Campus_buildings_-_hostel.jpg/1280px-IIT_Palakkad_Campus_buildings_-_hostel.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/IIT_Palakkad_Campus_buildings_-_hostel.jpg/330px-IIT_Palakkad_Campus_buildings_-_hostel.jpg', '["Core engineering","Hilly green campus","Close-knit batches","Kerala''s IIT"]'::jsonb, '{"ranking":64,"reputation":2,"avgPackage":16,"medianPackage":12.8,"highestPackage":42,"placementRate":72,"recruiters":1,"fees":9,"feesRange":"₹8–10 L","facultyRatio":12,"research":79,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":504,"location":"Rural · Palakkad"}'::jsonb),
('nit-meghalaya', 'NIT Meghalaya', 'Shillong, Meghalaya', 'Engineering & Technology', '#38bdf8', 'A scenic NIT in the Northeast hills.', '', '', '["Hill-station campus","Small batches","Emerging research"]'::jsonb, '{"ranking":68,"reputation":1,"avgPackage":9,"medianPackage":7.2,"highestPackage":35,"placementRate":65,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":66,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":300,"location":"Hill town · Shillong"}'::jsonb),
('nit-raipur', 'NIT Raipur', 'Raipur, Chhattisgarh', 'Engineering & Technology', '#06b6d4', 'Chhattisgarh''s NIT with a green campus.', 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Green_campus%2C_NIT_Raipur.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Green_campus%2C_NIT_Raipur.png/330px-Green_campus%2C_NIT_Raipur.png', '["Mining & Metallurgy","Green campus","Central India"]'::jsonb, '{"ranking":71,"reputation":2,"avgPackage":11,"medianPackage":8.8,"highestPackage":45,"placementRate":72,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":68,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":142,"location":"Urban · Raipur"}'::jsonb),
('nit-bhopal', 'MANIT Bhopal', 'Bhopal, Madhya Pradesh', 'Engineering & Technology', '#0ea5e9', 'A large lakeside NIT in the City of Lakes.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/MANIT_Main_Building.jpg/1280px-MANIT_Main_Building.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/MANIT_Main_Building.jpg/330px-MANIT_Main_Building.jpg', '["Sprawling campus","Core engineering","Lakeside setting"]'::jsonb, '{"ranking":72,"reputation":2,"avgPackage":13,"medianPackage":10.4,"highestPackage":64,"placementRate":78,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":71,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":650,"location":"Urban · Bhopal"}'::jsonb),
('iit-bhilai', 'IIT Bhilai', 'Bhilai, Chhattisgarh', 'Engineering & Technology', '#fb7185', 'Central India''s IIT with a creative streak.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/IIT_Bhilai_Acad_Block.jpg/1280px-IIT_Bhilai_Acad_Block.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/IIT_Bhilai_Acad_Block.jpg/330px-IIT_Bhilai_Acad_Block.jpg', '["Data science focus","Creative-arts electives","New campus","Central India''s IIT"]'::jsonb, '{"ranking":73,"reputation":2,"avgPackage":12.5,"medianPackage":10,"highestPackage":49,"placementRate":68,"recruiters":1,"fees":9,"feesRange":"₹8–10 L","facultyRatio":12,"research":78,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":445,"location":"Urban · Bhilai"}'::jsonb),
('nit-srinagar', 'NIT Srinagar', 'Srinagar, J&K', 'Engineering & Technology', '#22d3ee', 'A NIT on the banks of Dal Lake.', '', '', '["Stunning valley setting","Core branches","Dal Lake campus"]'::jsonb, '{"ranking":79,"reputation":2,"avgPackage":9,"medianPackage":7.2,"highestPackage":35,"placementRate":70,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":68,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":24,"location":"Valley · Srinagar"}'::jsonb),
('nit-kurukshetra', 'NIT Kurukshetra', 'Kurukshetra, Haryana', 'Engineering & Technology', '#2dd4bf', 'A solid NIT near the Delhi-NCR belt.', '', '', '["Core engineering","NCR proximity","Strong alumni"]'::jsonb, '{"ranking":81,"reputation":2,"avgPackage":12,"medianPackage":9.6,"highestPackage":50,"placementRate":78,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":72,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":300,"location":"Suburban · Kurukshetra"}'::jsonb),
('nit-agartala', 'NIT Agartala', 'Agartala, Tripura', 'Engineering & Technology', '#14b8a6', 'A Northeast NIT with a calm campus.', '', '', '["Core branches","Affordable","Quiet campus"]'::jsonb, '{"ranking":82,"reputation":1,"avgPackage":9,"medianPackage":7.2,"highestPackage":35,"placementRate":68,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":66,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":350,"location":"Suburban · Agartala"}'::jsonb),
('nit-puducherry', 'NIT Puducherry', 'Karaikal, Puducherry', 'Engineering & Technology', '#60a5fa', 'A coastal NIT in the south.', '', '', '["Coastal campus","Small batches","Emerging"]'::jsonb, '{"ranking":97,"reputation":1,"avgPackage":9,"medianPackage":7.2,"highestPackage":35,"placementRate":65,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":65,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":258,"location":"Coastal · Karaikal"}'::jsonb),
('nit-jamshedpur', 'NIT Jamshedpur', 'Jamshedpur, Jharkhand', 'Engineering & Technology', '#3b82f6', 'An older NIT in India''s steel city.', '', '', '["Metallurgy","Industry links","Strong core"]'::jsonb, '{"ranking":101,"reputation":2,"avgPackage":12,"medianPackage":9.6,"highestPackage":82,"placementRate":78,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":14,"research":70,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":325,"location":"Urban · Jamshedpur"}'::jsonb),
('iit-goa', 'IIT Goa', 'Goa', 'Engineering & Technology', '#f472b6', 'The smallest IIT, by the Goan coast.', '', '', '["Smallest IIT","Coastal campus","Core branches","Close mentorship"]'::jsonb, '{"ranking":999,"reputation":2,"avgPackage":13,"medianPackage":10.4,"highestPackage":50,"placementRate":70,"recruiters":1,"fees":9,"feesRange":"₹8–10 L","facultyRatio":11,"research":78,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":320,"location":"Coastal · Goa"}'::jsonb),
('iit-dharwad', 'IIT Dharwad', 'Dharwad, Karnataka', 'Engineering & Technology', '#c084fc', 'Karnataka''s IIT, young and growing.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/IIT_DHARWAD.jpg/1280px-IIT_DHARWAD.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/IIT_DHARWAD.jpg/330px-IIT_DHARWAD.jpg', '["Core engineering","Emerging research","New campus","Karnataka''s IIT"]'::jsonb, '{"ranking":101,"reputation":2,"avgPackage":12.63,"medianPackage":10.1,"highestPackage":52,"placementRate":70,"recruiters":1,"fees":9,"feesRange":"₹8–10 L","facultyRatio":12,"research":77,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Advanced","campusAcres":470,"location":"Suburban · Dharwad"}'::jsonb),
('nit-hamirpur', 'NIT Hamirpur', 'Hamirpur, Himachal Pradesh', 'Engineering & Technology', '#0891b2', 'A NIT in the Himalayan foothills.', '', '', '["Hill campus","Core branches","Scenic setting"]'::jsonb, '{"ranking":101,"reputation":2,"avgPackage":11,"medianPackage":8.8,"highestPackage":45,"placementRate":74,"recruiters":2,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":68,"infrastructure":2,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":320,"location":"Hill town · Hamirpur"}'::jsonb),
('nit-andhra', 'NIT Andhra Pradesh', 'Tadepalligudem, Andhra Pradesh', 'Engineering & Technology', '#0e7490', 'One of the newest NITs, growing fast.', '', '', '["New campus","Core engineering","Small batches"]'::jsonb, '{"ranking":201,"reputation":1,"avgPackage":9,"medianPackage":7.2,"highestPackage":42,"placementRate":68,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":64,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":150,"location":"Suburban · Tadepalligudem"}'::jsonb),
('nit-goa', 'NIT Goa', 'Goa', 'Engineering & Technology', '#0284c7', 'A coastal NIT in sunny Goa.', '', '', '["Coastal setting","Small batches","New campus"]'::jsonb, '{"ranking":101,"reputation":1,"avgPackage":9,"medianPackage":7.2,"highestPackage":38,"placementRate":65,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":15,"research":64,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":300,"location":"Coastal · Goa"}'::jsonb),
('nit-uttarakhand', 'NIT Uttarakhand', 'Srinagar, Uttarakhand', 'Engineering & Technology', '#2563eb', 'A young NIT in the Garhwal Himalayas.', '', '', '["Mountain campus","Core branches","Emerging"]'::jsonb, '{"ranking":101,"reputation":1,"avgPackage":8,"medianPackage":6.4,"highestPackage":30,"placementRate":60,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":16,"research":62,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":100,"location":"Hill town · Srinagar"}'::jsonb),
('nit-manipur', 'NIT Manipur', 'Imphal, Manipur', 'Engineering & Technology', '#38bdf8', 'A newer Northeast NIT.', '', '', '["Small batches","Core engineering","Emerging research"]'::jsonb, '{"ranking":101,"reputation":1,"avgPackage":7,"medianPackage":5.6,"highestPackage":28,"placementRate":58,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":16,"research":61,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":200,"location":"Suburban · Imphal"}'::jsonb),
('nit-sikkim', 'NIT Sikkim', 'Ravangla, Sikkim', 'Engineering & Technology', '#06b6d4', 'A NIT amid the Himalayan landscapes.', '', '', '["Mountain setting","Small batches","New campus"]'::jsonb, '{"ranking":151,"reputation":1,"avgPackage":8,"medianPackage":6.4,"highestPackage":28,"placementRate":58,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":16,"research":60,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":100,"location":"Hill town · Ravangla"}'::jsonb),
('nit-mizoram', 'NIT Mizoram', 'Aizawl, Mizoram', 'Engineering & Technology', '#0ea5e9', 'A young hill-station NIT.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/NIT_Mizoram_Lengui_Campus.jpg/1280px-NIT_Mizoram_Lengui_Campus.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/NIT_Mizoram_Lengui_Campus.jpg/330px-NIT_Mizoram_Lengui_Campus.jpg', '["Hill campus","Small batches","Emerging"]'::jsonb, '{"ranking":101,"reputation":1,"avgPackage":7,"medianPackage":5.6,"highestPackage":35,"placementRate":55,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":16,"research":60,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":190,"location":"Hill town · Aizawl"}'::jsonb),
('nit-nagaland', 'NIT Nagaland', 'Dimapur, Nagaland', 'Engineering & Technology', '#22d3ee', 'One of the newest NITs in the Northeast.', '', '', '["Small batches","Core branches","New campus"]'::jsonb, '{"ranking":151,"reputation":1,"avgPackage":5,"medianPackage":4,"highestPackage":14,"placementRate":55,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":16,"research":59,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":100,"location":"Hill town · Dimapur"}'::jsonb),
('nit-arunachal', 'NIT Arunachal Pradesh', 'Jote, Arunachal Pradesh', 'Engineering & Technology', '#2dd4bf', 'A frontier NIT in the eastern Himalayas.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/NIT_Arunachal_Pradesh_-_Main_Building_%28Temporary_Campus%29.JPG/1280px-NIT_Arunachal_Pradesh_-_Main_Building_%28Temporary_Campus%29.JPG', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/NIT_Arunachal_Pradesh_-_Main_Building_%28Temporary_Campus%29.JPG/330px-NIT_Arunachal_Pradesh_-_Main_Building_%28Temporary_Campus%29.JPG', '["Remote scenic campus","Small batches","Emerging"]'::jsonb, '{"ranking":101,"reputation":1,"avgPackage":7.2,"medianPackage":5.8,"highestPackage":58,"placementRate":55,"recruiters":1,"fees":6.25,"feesRange":"₹5.5–7 L","facultyRatio":16,"research":59,"infrastructure":1,"accreditation":"INI (exempt)","exam":"JEE Main","campusAcres":301,"location":"Hill town · Jote"}'::jsonb)
on conflict (id) do update set
  name=excluded.name, city=excluded.city, type=excluded.type, accent=excluded.accent,
  tagline=excluded.tagline, image=excluded.image, thumb=excluded.thumb,
  specialities=excluded.specialities, factors=excluded.factors;


-- ─────────────────────────────────────────────────────────────
--  Migration 002 — cutoffs, branch placements, structured costs
--  Run once in Supabase SQL Editor. Safe to re-run.
-- ─────────────────────────────────────────────────────────────

-- 1) Cutoffs: college × exam × year × round × branch × category × quota × gender
create table if not exists public.cutoffs (
  id            bigint generated always as identity primary key,
  college_id    text not null references public.colleges(id) on delete cascade,
  exam          text not null,                   -- 'JEE Advanced'|'JEE Main'|'BITSAT'|'VITEEE'|...
  year          int  not null,
  round         text not null default 'final',   -- '1'..'6' | 'final'
  branch        text not null,                   -- 'CSE','ECE','EE','ME','CE','CHE'
  category      text not null default 'General', -- 'General'|'EWS'|'OBC-NCL'|'SC'|'ST'
  quota         text not null default 'AI',      -- 'AI' (IIT/all-India) | 'OS' | 'HS' (NIT quotas)
  gender        text not null default 'GN',      -- 'GN' | 'Female'
  closing_rank  int,                             -- rank-based exams (category rank for reserved)
  closing_score numeric,                         -- score-based exams (BITSAT marks)
  unique (college_id, exam, year, round, branch, category, quota, gender)
);
create index if not exists cutoffs_predictor_idx
  on public.cutoffs (exam, year, category, branch, closing_rank);

alter table public.cutoffs enable row level security;
drop policy if exists "public read cutoffs" on public.cutoffs;
create policy "public read cutoffs" on public.cutoffs for select using (true);
drop policy if exists "admin write cutoffs" on public.cutoffs;
create policy "admin write cutoffs" on public.cutoffs for all to authenticated
  using      ( (auth.jwt() ->> 'email') = 'rayanrayanhussain9@gmail.com' )
  with check ( (auth.jwt() ->> 'email') = 'rayanrayanhussain9@gmail.com' );

-- 2) Branch-wise placements: college × branch × year
create table if not exists public.branch_placements (
  id             bigint generated always as identity primary key,
  college_id     text not null references public.colleges(id) on delete cascade,
  branch         text not null,
  year           int  not null,
  median_package numeric,
  avg_package    numeric,
  percent_placed numeric,
  top_recruiters jsonb default '[]'::jsonb,
  unique (college_id, branch, year)
);
alter table public.branch_placements enable row level security;
drop policy if exists "public read branch_placements" on public.branch_placements;
create policy "public read branch_placements" on public.branch_placements for select using (true);
drop policy if exists "admin write branch_placements" on public.branch_placements;
create policy "admin write branch_placements" on public.branch_placements for all to authenticated
  using      ( (auth.jwt() ->> 'email') = 'rayanrayanhussain9@gmail.com' )
  with check ( (auth.jwt() ->> 'email') = 'rayanrayanhussain9@gmail.com' );

-- 3) Structured 4-year cost on colleges (₹ lakhs)
alter table public.colleges add column if not exists costs jsonb default '{}'::jsonb;


-- Cutoffs seed: JoSAA/JAC/BITSAT 2024, final round (R5), General GN. Safe to re-run.
insert into public.cutoffs (college_id,exam,year,round,branch,category,quota,gender,closing_rank,closing_score) values
('iit-bombay','JEE Advanced',2024,'5','CSE','General','AI','GN',68,null),
('iit-bombay','JEE Advanced',2024,'5','EE','General','AI','GN',468,null),
('iit-bombay','JEE Advanced',2024,'5','ME','General','AI','GN',1739,null),
('iit-bombay','JEE Advanced',2024,'5','CE','General','AI','GN',3200,null),
('iit-bombay','JEE Advanced',2024,'5','CHE','General','AI','GN',2221,null),
('iit-delhi','JEE Advanced',2024,'5','CSE','General','AI','GN',116,null),
('iit-delhi','JEE Advanced',2024,'5','EE','General','AI','GN',573,null),
('iit-delhi','JEE Advanced',2024,'5','ME','General','AI','GN',1846,null),
('iit-delhi','JEE Advanced',2024,'5','CE','General','AI','GN',3860,null),
('iit-delhi','JEE Advanced',2024,'5','CHE','General','AI','GN',2371,null),
('iit-madras','JEE Advanced',2024,'5','CSE','General','AI','GN',159,null),
('iit-madras','JEE Advanced',2024,'5','EE','General','AI','GN',964,null),
('iit-madras','JEE Advanced',2024,'5','ME','General','AI','GN',2470,null),
('iit-madras','JEE Advanced',2024,'5','CE','General','AI','GN',4519,null),
('iit-madras','JEE Advanced',2024,'5','CHE','General','AI','GN',3311,null),
('iit-kanpur','JEE Advanced',2024,'5','CSE','General','AI','GN',252,null),
('iit-kanpur','JEE Advanced',2024,'5','EE','General','AI','GN',1078,null),
('iit-kanpur','JEE Advanced',2024,'5','ME','General','AI','GN',2743,null),
('iit-kanpur','JEE Advanced',2024,'5','CE','General','AI','GN',4970,null),
('iit-kanpur','JEE Advanced',2024,'5','CHE','General','AI','GN',3583,null),
('iit-kharagpur','JEE Advanced',2024,'5','CSE','General','AI','GN',415,null),
('iit-kharagpur','JEE Advanced',2024,'5','ECE','General','AI','GN',898,null),
('iit-kharagpur','JEE Advanced',2024,'5','EE','General','AI','GN',1449,null),
('iit-kharagpur','JEE Advanced',2024,'5','ME','General','AI','GN',3478,null),
('iit-kharagpur','JEE Advanced',2024,'5','CE','General','AI','GN',5528,null),
('iit-kharagpur','JEE Advanced',2024,'5','CHE','General','AI','GN',4341,null),
('iit-roorkee','JEE Advanced',2024,'5','CSE','General','AI','GN',481,null),
('iit-roorkee','JEE Advanced',2024,'5','ECE','General','AI','GN',1481,null),
('iit-roorkee','JEE Advanced',2024,'5','EE','General','AI','GN',2015,null),
('iit-roorkee','JEE Advanced',2024,'5','ME','General','AI','GN',3717,null),
('iit-roorkee','JEE Advanced',2024,'5','CE','General','AI','GN',5532,null),
('iit-roorkee','JEE Advanced',2024,'5','CHE','General','AI','GN',4801,null),
('iit-guwahati','JEE Advanced',2024,'5','CSE','General','AI','GN',623,null),
('iit-guwahati','JEE Advanced',2024,'5','ECE','General','AI','GN',1480,null),
('iit-guwahati','JEE Advanced',2024,'5','EE','General','AI','GN',2197,null),
('iit-guwahati','JEE Advanced',2024,'5','ME','General','AI','GN',4179,null),
('iit-guwahati','JEE Advanced',2024,'5','CE','General','AI','GN',6093,null),
('iit-guwahati','JEE Advanced',2024,'5','CHE','General','AI','GN',5296,null),
('iit-hyderabad','JEE Advanced',2024,'5','CSE','General','AI','GN',656,null),
('iit-hyderabad','JEE Advanced',2024,'5','EE','General','AI','GN',1500,null),
('iit-hyderabad','JEE Advanced',2024,'5','ME','General','AI','GN',3900,null),
('iit-hyderabad','JEE Advanced',2024,'5','CE','General','AI','GN',6000,null),
('iit-hyderabad','JEE Advanced',2024,'5','CHE','General','AI','GN',5100,null),
('iit-bhu','JEE Advanced',2024,'5','CSE','General','AI','GN',1109,null),
('iit-bhu','JEE Advanced',2024,'5','ECE','General','AI','GN',2005,null),
('iit-bhu','JEE Advanced',2024,'5','EE','General','AI','GN',2907,null),
('iit-bhu','JEE Advanced',2024,'5','ME','General','AI','GN',4938,null),
('iit-bhu','JEE Advanced',2024,'5','CE','General','AI','GN',7093,null),
('iit-bhu','JEE Advanced',2024,'5','CHE','General','AI','GN',6060,null),
('iit-dhanbad','JEE Advanced',2024,'5','CSE','General','AI','GN',1623,null),
('iit-dhanbad','JEE Advanced',2024,'5','ECE','General','AI','GN',2822,null),
('iit-dhanbad','JEE Advanced',2024,'5','EE','General','AI','GN',3752,null),
('iit-dhanbad','JEE Advanced',2024,'5','ME','General','AI','GN',5455,null),
('iit-dhanbad','JEE Advanced',2024,'5','CE','General','AI','GN',7716,null),
('iit-dhanbad','JEE Advanced',2024,'5','CHE','General','AI','GN',6716,null),
('iit-indore','JEE Advanced',2024,'5','CSE','General','AI','GN',1360,null),
('iit-indore','JEE Advanced',2024,'5','EE','General','AI','GN',2860,null),
('iit-indore','JEE Advanced',2024,'5','ME','General','AI','GN',4831,null),
('iit-indore','JEE Advanced',2024,'5','CE','General','AI','GN',7200,null),
('iit-gandhinagar','JEE Advanced',2024,'5','CSE','General','AI','GN',1442,null),
('iit-gandhinagar','JEE Advanced',2024,'5','EE','General','AI','GN',3096,null),
('iit-gandhinagar','JEE Advanced',2024,'5','ME','General','AI','GN',5065,null),
('iit-gandhinagar','JEE Advanced',2024,'5','CE','General','AI','GN',6465,null),
('iit-gandhinagar','JEE Advanced',2024,'5','CHE','General','AI','GN',5842,null),
('iit-ropar','JEE Advanced',2024,'5','CSE','General','AI','GN',2135,null),
('iit-ropar','JEE Advanced',2024,'5','EE','General','AI','GN',3746,null),
('iit-ropar','JEE Advanced',2024,'5','ME','General','AI','GN',5748,null),
('iit-ropar','JEE Advanced',2024,'5','CE','General','AI','GN',7276,null),
('iit-ropar','JEE Advanced',2024,'5','CHE','General','AI','GN',6926,null),
('iit-patna','JEE Advanced',2024,'5','CSE','General','AI','GN',2342,null),
('iit-patna','JEE Advanced',2024,'5','ECE','General','AI','GN',3775,null),
('iit-patna','JEE Advanced',2024,'5','EE','General','AI','GN',4319,null),
('iit-patna','JEE Advanced',2024,'5','ME','General','AI','GN',6270,null),
('iit-patna','JEE Advanced',2024,'5','CE','General','AI','GN',7807,null),
('iit-patna','JEE Advanced',2024,'5','CHE','General','AI','GN',7524,null),
('iit-bhubaneswar','JEE Advanced',2024,'5','CSE','General','AI','GN',2422,null),
('iit-bhubaneswar','JEE Advanced',2024,'5','ECE','General','AI','GN',3811,null),
('iit-bhubaneswar','JEE Advanced',2024,'5','EE','General','AI','GN',4482,null),
('iit-bhubaneswar','JEE Advanced',2024,'5','ME','General','AI','GN',6284,null),
('iit-bhubaneswar','JEE Advanced',2024,'5','CE','General','AI','GN',7772,null),
('iit-bhubaneswar','JEE Advanced',2024,'5','CHE','General','AI','GN',7368,null),
('iit-jodhpur','JEE Advanced',2024,'5','CSE','General','AI','GN',2565,null),
('iit-jodhpur','JEE Advanced',2024,'5','EE','General','AI','GN',4450,null),
('iit-jodhpur','JEE Advanced',2024,'5','ME','General','AI','GN',6169,null),
('iit-jodhpur','JEE Advanced',2024,'5','CE','General','AI','GN',7871,null),
('iit-jodhpur','JEE Advanced',2024,'5','CHE','General','AI','GN',7439,null),
('iit-mandi','JEE Advanced',2024,'5','CSE','General','AI','GN',2764,null),
('iit-mandi','JEE Advanced',2024,'5','EE','General','AI','GN',4676,null),
('iit-mandi','JEE Advanced',2024,'5','ME','General','AI','GN',6355,null),
('iit-mandi','JEE Advanced',2024,'5','CE','General','AI','GN',7997,null),
('iit-jammu','JEE Advanced',2024,'5','CSE','General','AI','GN',3079,null),
('iit-jammu','JEE Advanced',2024,'5','EE','General','AI','GN',5100,null),
('iit-jammu','JEE Advanced',2024,'5','ME','General','AI','GN',6819,null),
('iit-jammu','JEE Advanced',2024,'5','CE','General','AI','GN',8225,null),
('iit-jammu','JEE Advanced',2024,'5','CHE','General','AI','GN',7789,null),
('iit-tirupati','JEE Advanced',2024,'5','CSE','General','AI','GN',3646,null),
('iit-tirupati','JEE Advanced',2024,'5','EE','General','AI','GN',5439,null),
('iit-tirupati','JEE Advanced',2024,'5','ME','General','AI','GN',7031,null),
('iit-tirupati','JEE Advanced',2024,'5','CE','General','AI','GN',8471,null),
('iit-tirupati','JEE Advanced',2024,'5','CHE','General','AI','GN',8069,null),
('iit-palakkad','JEE Advanced',2024,'5','CSE','General','AI','GN',3733,null),
('iit-palakkad','JEE Advanced',2024,'5','EE','General','AI','GN',5629,null),
('iit-palakkad','JEE Advanced',2024,'5','ME','General','AI','GN',7189,null),
('iit-palakkad','JEE Advanced',2024,'5','CE','General','AI','GN',8637,null),
('iit-bhilai','JEE Advanced',2024,'5','CSE','General','AI','GN',4045,null),
('iit-bhilai','JEE Advanced',2024,'5','EE','General','AI','GN',5896,null),
('iit-bhilai','JEE Advanced',2024,'5','ME','General','AI','GN',7422,null),
('iit-goa','JEE Advanced',2024,'5','CSE','General','AI','GN',4083,null),
('iit-goa','JEE Advanced',2024,'5','EE','General','AI','GN',5936,null),
('iit-goa','JEE Advanced',2024,'5','ME','General','AI','GN',7442,null),
('iit-dharwad','JEE Advanced',2024,'5','CSE','General','AI','GN',4402,null),
('iit-dharwad','JEE Advanced',2024,'5','EE','General','AI','GN',6111,null),
('iit-dharwad','JEE Advanced',2024,'5','ME','General','AI','GN',7605,null),
('nit-trichy','JEE Main',2024,'5','CSE','General','OS','GN',1178,null),
('nit-trichy','JEE Main',2024,'5','ECE','General','OS','GN',2585,null),
('nit-trichy','JEE Main',2024,'5','EE','General','OS','GN',3800,null),
('nit-trichy','JEE Main',2024,'5','ME','General','OS','GN',6200,null),
('nit-trichy','JEE Main',2024,'5','CE','General','OS','GN',10500,null),
('nit-trichy','JEE Main',2024,'5','CHE','General','OS','GN',8500,null),
('nit-surathkal','JEE Main',2024,'5','CSE','General','OS','GN',1465,null),
('nit-surathkal','JEE Main',2024,'5','ECE','General','OS','GN',3200,null),
('nit-surathkal','JEE Main',2024,'5','EE','General','OS','GN',4800,null),
('nit-surathkal','JEE Main',2024,'5','ME','General','OS','GN',7500,null),
('nit-surathkal','JEE Main',2024,'5','CE','General','OS','GN',12500,null),
('nit-surathkal','JEE Main',2024,'5','CHE','General','OS','GN',10500,null),
('nit-warangal','JEE Main',2024,'5','CSE','General','OS','GN',1683,null),
('nit-warangal','JEE Main',2024,'5','ECE','General','OS','GN',3600,null),
('nit-warangal','JEE Main',2024,'5','EE','General','OS','GN',5300,null),
('nit-warangal','JEE Main',2024,'5','ME','General','OS','GN',8300,null),
('nit-warangal','JEE Main',2024,'5','CE','General','OS','GN',13000,null),
('nit-warangal','JEE Main',2024,'5','CHE','General','OS','GN',11000,null),
('nit-rourkela','JEE Main',2024,'5','CSE','General','OS','GN',2905,null),
('nit-rourkela','JEE Main',2024,'5','ECE','General','OS','GN',5900,null),
('nit-rourkela','JEE Main',2024,'5','EE','General','OS','GN',8000,null),
('nit-rourkela','JEE Main',2024,'5','ME','General','OS','GN',12000,null),
('nit-rourkela','JEE Main',2024,'5','CE','General','OS','GN',18000,null),
('nit-rourkela','JEE Main',2024,'5','CHE','General','OS','GN',15000,null),
('nit-calicut','JEE Main',2024,'5','CSE','General','OS','GN',3169,null),
('nit-calicut','JEE Main',2024,'5','ECE','General','OS','GN',6500,null),
('nit-calicut','JEE Main',2024,'5','EE','General','OS','GN',9000,null),
('nit-calicut','JEE Main',2024,'5','ME','General','OS','GN',13000,null),
('nit-calicut','JEE Main',2024,'5','CE','General','OS','GN',19000,null),
('nit-calicut','JEE Main',2024,'5','CHE','General','OS','GN',16500,null),
('nit-allahabad','JEE Main',2024,'5','CSE','General','OS','GN',4166,null),
('nit-allahabad','JEE Main',2024,'5','ECE','General','OS','GN',7800,null),
('nit-allahabad','JEE Main',2024,'5','EE','General','OS','GN',10500,null),
('nit-allahabad','JEE Main',2024,'5','ME','General','OS','GN',15500,null),
('nit-allahabad','JEE Main',2024,'5','CE','General','OS','GN',22000,null),
('nit-allahabad','JEE Main',2024,'5','CHE','General','OS','GN',19500,null),
('nit-jaipur','JEE Main',2024,'5','CSE','General','OS','GN',4360,null),
('nit-jaipur','JEE Main',2024,'5','ECE','General','OS','GN',8500,null),
('nit-jaipur','JEE Main',2024,'5','EE','General','OS','GN',11500,null),
('nit-jaipur','JEE Main',2024,'5','ME','General','OS','GN',17000,null),
('nit-jaipur','JEE Main',2024,'5','CE','General','OS','GN',25000,null),
('nit-jaipur','JEE Main',2024,'5','CHE','General','OS','GN',22000,null),
('nit-nagpur','JEE Main',2024,'5','CSE','General','OS','GN',5665,null),
('nit-nagpur','JEE Main',2024,'5','ECE','General','OS','GN',10500,null),
('nit-nagpur','JEE Main',2024,'5','EE','General','OS','GN',14000,null),
('nit-nagpur','JEE Main',2024,'5','ME','General','OS','GN',21000,null),
('nit-nagpur','JEE Main',2024,'5','CE','General','OS','GN',30000,null),
('nit-nagpur','JEE Main',2024,'5','CHE','General','OS','GN',26000,null),
('nit-delhi','JEE Main',2024,'5','CSE','General','OS','GN',6500,null),
('nit-delhi','JEE Main',2024,'5','ECE','General','OS','GN',12000,null),
('nit-delhi','JEE Main',2024,'5','EE','General','OS','GN',16000,null),
('nit-surat','JEE Main',2024,'5','CSE','General','OS','GN',6857,null),
('nit-surat','JEE Main',2024,'5','ECE','General','OS','GN',12500,null),
('nit-surat','JEE Main',2024,'5','EE','General','OS','GN',16500,null),
('nit-surat','JEE Main',2024,'5','ME','General','OS','GN',25000,null),
('nit-surat','JEE Main',2024,'5','CE','General','OS','GN',34000,null),
('nit-surat','JEE Main',2024,'5','CHE','General','OS','GN',30000,null),
('nit-kurukshetra','JEE Main',2024,'5','CSE','General','OS','GN',7000,null),
('nit-kurukshetra','JEE Main',2024,'5','ECE','General','OS','GN',13000,null),
('nit-kurukshetra','JEE Main',2024,'5','EE','General','OS','GN',17500,null),
('nit-kurukshetra','JEE Main',2024,'5','ME','General','OS','GN',26000,null),
('nit-kurukshetra','JEE Main',2024,'5','CE','General','OS','GN',36000,null),
('nit-bhopal','JEE Main',2024,'5','CSE','General','OS','GN',8500,null),
('nit-bhopal','JEE Main',2024,'5','ECE','General','OS','GN',15500,null),
('nit-bhopal','JEE Main',2024,'5','EE','General','OS','GN',20500,null),
('nit-bhopal','JEE Main',2024,'5','ME','General','OS','GN',30000,null),
('nit-bhopal','JEE Main',2024,'5','CE','General','OS','GN',41000,null),
('nit-bhopal','JEE Main',2024,'5','CHE','General','OS','GN',36000,null),
('nit-jalandhar','JEE Main',2024,'5','CSE','General','OS','GN',9500,null),
('nit-jalandhar','JEE Main',2024,'5','ECE','General','OS','GN',17000,null),
('nit-jalandhar','JEE Main',2024,'5','EE','General','OS','GN',23000,null),
('nit-jalandhar','JEE Main',2024,'5','ME','General','OS','GN',33000,null),
('nit-jalandhar','JEE Main',2024,'5','CE','General','OS','GN',44000,null),
('nit-jalandhar','JEE Main',2024,'5','CHE','General','OS','GN',39000,null),
('nit-jamshedpur','JEE Main',2024,'5','CSE','General','OS','GN',10500,null),
('nit-jamshedpur','JEE Main',2024,'5','ECE','General','OS','GN',19000,null),
('nit-jamshedpur','JEE Main',2024,'5','EE','General','OS','GN',25000,null),
('nit-jamshedpur','JEE Main',2024,'5','ME','General','OS','GN',35000,null),
('nit-jamshedpur','JEE Main',2024,'5','CE','General','OS','GN',46000,null),
('nit-durgapur','JEE Main',2024,'5','CSE','General','OS','GN',12000,null),
('nit-durgapur','JEE Main',2024,'5','ECE','General','OS','GN',21000,null),
('nit-durgapur','JEE Main',2024,'5','EE','General','OS','GN',27000,null),
('nit-durgapur','JEE Main',2024,'5','ME','General','OS','GN',38000,null),
('nit-durgapur','JEE Main',2024,'5','CE','General','OS','GN',49000,null),
('nit-durgapur','JEE Main',2024,'5','CHE','General','OS','GN',44000,null),
('nit-patna','JEE Main',2024,'5','CSE','General','OS','GN',13500,null),
('nit-patna','JEE Main',2024,'5','ECE','General','OS','GN',23000,null),
('nit-patna','JEE Main',2024,'5','EE','General','OS','GN',29000,null),
('nit-patna','JEE Main',2024,'5','ME','General','OS','GN',41000,null),
('nit-patna','JEE Main',2024,'5','CE','General','OS','GN',52000,null),
('nit-hamirpur','JEE Main',2024,'5','CSE','General','OS','GN',14500,null),
('nit-hamirpur','JEE Main',2024,'5','ECE','General','OS','GN',25000,null),
('nit-hamirpur','JEE Main',2024,'5','EE','General','OS','GN',31000,null),
('nit-hamirpur','JEE Main',2024,'5','ME','General','OS','GN',43000,null),
('nit-hamirpur','JEE Main',2024,'5','CE','General','OS','GN',54000,null),
('nit-hamirpur','JEE Main',2024,'5','CHE','General','OS','GN',49000,null),
('nit-raipur','JEE Main',2024,'5','CSE','General','OS','GN',16000,null),
('nit-raipur','JEE Main',2024,'5','ECE','General','OS','GN',27000,null),
('nit-raipur','JEE Main',2024,'5','EE','General','OS','GN',34000,null),
('nit-raipur','JEE Main',2024,'5','ME','General','OS','GN',46000,null),
('nit-raipur','JEE Main',2024,'5','CE','General','OS','GN',57000,null),
('nit-raipur','JEE Main',2024,'5','CHE','General','OS','GN',52000,null),
('nit-silchar','JEE Main',2024,'5','CSE','General','OS','GN',17500,null),
('nit-silchar','JEE Main',2024,'5','ECE','General','OS','GN',29000,null),
('nit-silchar','JEE Main',2024,'5','EE','General','OS','GN',36000,null),
('nit-silchar','JEE Main',2024,'5','ME','General','OS','GN',49000,null),
('nit-silchar','JEE Main',2024,'5','CE','General','OS','GN',60000,null),
('nit-agartala','JEE Main',2024,'5','CSE','General','OS','GN',25000,null),
('nit-agartala','JEE Main',2024,'5','ECE','General','OS','GN',40000,null),
('nit-agartala','JEE Main',2024,'5','EE','General','OS','GN',50000,null),
('nit-agartala','JEE Main',2024,'5','ME','General','OS','GN',65000,null),
('nit-agartala','JEE Main',2024,'5','CE','General','OS','GN',75000,null),
('nit-agartala','JEE Main',2024,'5','CHE','General','OS','GN',70000,null),
('nit-goa','JEE Main',2024,'5','CSE','General','OS','GN',27000,null),
('nit-goa','JEE Main',2024,'5','ECE','General','OS','GN',43000,null),
('nit-goa','JEE Main',2024,'5','EE','General','OS','GN',52000,null),
('nit-goa','JEE Main',2024,'5','ME','General','OS','GN',68000,null),
('nit-meghalaya','JEE Main',2024,'5','CSE','General','OS','GN',28000,null),
('nit-meghalaya','JEE Main',2024,'5','ECE','General','OS','GN',45000,null),
('nit-meghalaya','JEE Main',2024,'5','EE','General','OS','GN',55000,null),
('nit-meghalaya','JEE Main',2024,'5','ME','General','OS','GN',70000,null),
('nit-meghalaya','JEE Main',2024,'5','CE','General','OS','GN',80000,null),
('nit-puducherry','JEE Main',2024,'5','CSE','General','OS','GN',30000,null),
('nit-puducherry','JEE Main',2024,'5','ECE','General','OS','GN',48000,null),
('nit-puducherry','JEE Main',2024,'5','EE','General','OS','GN',58000,null),
('nit-puducherry','JEE Main',2024,'5','ME','General','OS','GN',72000,null),
('nit-puducherry','JEE Main',2024,'5','CE','General','OS','GN',82000,null),
('nit-uttarakhand','JEE Main',2024,'5','CSE','General','OS','GN',32000,null),
('nit-uttarakhand','JEE Main',2024,'5','ECE','General','OS','GN',50000,null),
('nit-uttarakhand','JEE Main',2024,'5','EE','General','OS','GN',60000,null),
('nit-uttarakhand','JEE Main',2024,'5','ME','General','OS','GN',75000,null),
('nit-uttarakhand','JEE Main',2024,'5','CE','General','OS','GN',85000,null),
('nit-andhra','JEE Main',2024,'5','CSE','General','OS','GN',33000,null),
('nit-andhra','JEE Main',2024,'5','ECE','General','OS','GN',52000,null),
('nit-andhra','JEE Main',2024,'5','EE','General','OS','GN',62000,null),
('nit-andhra','JEE Main',2024,'5','ME','General','OS','GN',78000,null),
('nit-andhra','JEE Main',2024,'5','CE','General','OS','GN',88000,null),
('nit-andhra','JEE Main',2024,'5','CHE','General','OS','GN',83000,null),
('nit-manipur','JEE Main',2024,'5','CSE','General','OS','GN',38000,null),
('nit-manipur','JEE Main',2024,'5','ECE','General','OS','GN',58000,null),
('nit-manipur','JEE Main',2024,'5','EE','General','OS','GN',68000,null),
('nit-manipur','JEE Main',2024,'5','ME','General','OS','GN',82000,null),
('nit-manipur','JEE Main',2024,'5','CE','General','OS','GN',92000,null),
('nit-sikkim','JEE Main',2024,'5','CSE','General','OS','GN',40000,null),
('nit-sikkim','JEE Main',2024,'5','ECE','General','OS','GN',60000,null),
('nit-sikkim','JEE Main',2024,'5','EE','General','OS','GN',70000,null),
('nit-sikkim','JEE Main',2024,'5','ME','General','OS','GN',84000,null),
('nit-sikkim','JEE Main',2024,'5','CE','General','OS','GN',94000,null),
('nit-mizoram','JEE Main',2024,'5','CSE','General','OS','GN',42000,null),
('nit-mizoram','JEE Main',2024,'5','ECE','General','OS','GN',62000,null),
('nit-mizoram','JEE Main',2024,'5','EE','General','OS','GN',72000,null),
('nit-mizoram','JEE Main',2024,'5','ME','General','OS','GN',86000,null),
('nit-mizoram','JEE Main',2024,'5','CE','General','OS','GN',96000,null),
('nit-nagaland','JEE Main',2024,'5','CSE','General','OS','GN',44000,null),
('nit-nagaland','JEE Main',2024,'5','ECE','General','OS','GN',64000,null),
('nit-nagaland','JEE Main',2024,'5','EE','General','OS','GN',74000,null),
('nit-nagaland','JEE Main',2024,'5','ME','General','OS','GN',88000,null),
('nit-nagaland','JEE Main',2024,'5','CE','General','OS','GN',98000,null),
('nit-arunachal','JEE Main',2024,'5','CSE','General','OS','GN',46000,null),
('nit-arunachal','JEE Main',2024,'5','ECE','General','OS','GN',66000,null),
('nit-arunachal','JEE Main',2024,'5','EE','General','OS','GN',76000,null),
('nit-arunachal','JEE Main',2024,'5','ME','General','OS','GN',90000,null),
('nit-arunachal','JEE Main',2024,'5','CE','General','OS','GN',99000,null),
('nit-srinagar','JEE Main',2024,'5','CSE','General','OS','GN',45000,null),
('nit-srinagar','JEE Main',2024,'5','ECE','General','OS','GN',60000,null),
('nit-srinagar','JEE Main',2024,'5','EE','General','OS','GN',70000,null),
('nit-srinagar','JEE Main',2024,'5','ME','General','OS','GN',85000,null),
('nit-srinagar','JEE Main',2024,'5','CE','General','OS','GN',95000,null),
('iiit-hyderabad','JEE Main',2024,'5','CSE','General','AI','GN',1500,null),
('iiit-hyderabad','JEE Main',2024,'5','ECE','General','AI','GN',2800,null),
('dtu','JEE Main',2024,'5','CSE','General','OS','GN',4000,null),
('dtu','JEE Main',2024,'5','ECE','General','OS','GN',7500,null),
('dtu','JEE Main',2024,'5','EE','General','OS','GN',11000,null),
('dtu','JEE Main',2024,'5','ME','General','OS','GN',20000,null),
('dtu','JEE Main',2024,'5','CE','General','OS','GN',32000,null),
('bits-pilani','BITSAT',2024,'5','CSE','General','AI','GN',null,327),
('bits-pilani','BITSAT',2024,'5','ECE','General','AI','GN',null,300),
('bits-pilani','BITSAT',2024,'5','EE','General','AI','GN',null,292),
('bits-pilani','BITSAT',2024,'5','ME','General','AI','GN',null,244),
('bits-pilani','BITSAT',2024,'5','CHE','General','AI','GN',null,224),
('vit-vellore','VITEEE',2024,'5','CSE','General','AI','GN',25000,null),
('vit-vellore','VITEEE',2024,'5','ECE','General','AI','GN',60000,null),
('vit-vellore','VITEEE',2024,'5','EE','General','AI','GN',75000,null),
('vit-vellore','VITEEE',2024,'5','ME','General','AI','GN',100000,null),
('vit-vellore','VITEEE',2024,'5','CE','General','AI','GN',110000,null)
on conflict (college_id,exam,year,round,branch,category,quota,gender) do update set
  closing_rank=excluded.closing_rank, closing_score=excluded.closing_score;
